### ISSUE TITLE
For the older version of Jython

### ISSUE THREAD

**Issue by xssssrf** [bayotop/off-by-slash#1]
for the older version of jython,add "from __future__ import with_statement" at  the first line in the off-by-slash.py

**Comment by bayotop** [comment]
I'm not sure this is something I should do.

Could you please elaborate on what versions have problems with "with" statements? Is this still something people commonly run into? Shouldn't those affected update their environment instead?

**Comment by 0xaud** [comment]
Facing 
         java.lang.Exception: Failed to open Jython JAR file
	at burp.f_a.<init>(Unknown Source)
	at burp.p9.a(Unknown Source)
	at burp.a7a.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bayotop** [comment]
@rudrasingh99  This happens when you have a Jython file location configured, but Burp isn't able to open the file. To resolve the issue please check Burp's documentation / forums.

Additionally, in future please create a new issue instead of posting to an existing unrelated one to prevent confusion. Thank you.
